---
# tasks file for vector-role
- name: Check if vector dir exists
  ansible.builtin.stat: path="{{ vector_dir }}"
  register: vector_dir_stat

- name: Create dir for vector installation
  ansible.builtin.file:
    path: "{{ vector_dir }}"
    state: directory
    owner: "root"
    group: "root"
    mode: '0755'
  when: not vector_dir_stat.stat.exists

- name: Clean up dir for vector installation
  ansible.builtin.file:
    state: absent
    path: "{{ vector_dir }}/"
  when: vector_dir_stat.stat.exists

- name: Get vector distrib
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-x86_64-unknown-linux-musl.tar.gz"
    dest: "{{ vector_dir }}/vector-{{ vector_version }}-x86_64-unknown-linux-musl.tar.gz"
    mode: '0644'

- name: Extract archive
  ansible.builtin.unarchive:
    src: "{{ vector_dir }}/vector-{{ vector_version }}-x86_64-unknown-linux-musl.tar.gz"
    dest: "{{ vector_dir }}"
    copy: false # if true ansible would try to copy the archive from controller

- name: Check if archive folder is empty
  ansible.builtin.stat: path="{{ vector_dir }}/vector-x86_64-unknown-linux-musl/"
  register: archive_dir_stat

- name: Move to vector_dir
  ansible.builtin.shell:
    cmd: 'mv {{ vector_dir }}/vector-x86_64-unknown-linux-musl/* /opt/vector/'
  when: archive_dir_stat

- name: Recursively remove vector archive directory
  ansible.builtin.file:
    path: /opt/vector/vector-x86_64-unknown-linux-musl
    state: absent
  when: archive_dir_stat

# this task do not pass lint test but it depends on var value which can be changed every new playbook run
- name: Add another bin dir to system-wide $PATH
  ansible.builtin.shell:
    cmd: 'echo "PATH=$PATH:{{ vector_dir }}" > /etc/profile.d/vector-path.sh'

- name: Check if sym link for vector exists in /usr/bin
  ansible.builtin.stat: path="/usr/bin/vector"
  register: vector_bin_stat

- name: Replace sym link for vector
  block:
    - name: Delete old vector symlink in /usr/bin
      ansible.builtin.file:
        path: "/usr/bin/vector"
        state: absent

    - name: Add vector symlink to /usr/bin
      ansible.builtin.file:
        src: "{{ vector_dir }}/bin/vector"
        dest: "/usr/bin/vector"
        state: link

  when: vector_bin_stat

- name: Add vector symlink to /usr/bin
  ansible.builtin.file:
    src: "{{ vector_dir }}/bin/vector"
    dest: "/usr/bin/vector"
    state: link
  when: not vector_bin_stat
